name: Typos
on: [pull_request]

jobs:
  run:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Run Typos
        uses: crate-ci/typos@master
